# -*- coding: utf-8 -*-
"""titanic

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Hdo3K8x4EHopfrnOSjyAWtoA9GQeeqJR
"""

from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/train.csv')
df.head()

df.isnull().sum()

# Ageは中央値で補完
df["Age"] = df["Age"].fillna(df["Age"].median())

# Embarkedは最頻値で補完
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Cabinは欠損が多すぎるので削除
df = df.drop("Cabin", axis=1)



df.isnull().sum()

df = df.drop(["PassengerId", "Name", "Ticket"], axis=1)

df = pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True)

df.columns

import matplotlib.pyplot as plt
import pandas as pd

# Survived以外の特徴量
features = [col for col in df.columns if col != "Survived"]

for col in features:
    plt.figure(figsize=(6, 4))

    # AgeとFareは連続値なので、区間に分ける
    if col in ["Age", "Fare"]:
        temp = df.copy()
        temp[col + "_bin"] = pd.qcut(temp[col], q=5, duplicates="drop")

        temp.groupby(col + "_bin")["Survived"].mean().plot(kind="bar")
        plt.title(f"Survival Rate by {col}")
        plt.xlabel(col)
        plt.ylabel("Survival Rate")
        plt.xticks(rotation=45)

    # それ以外はカテゴリとして扱う
    else:
        df.groupby(col)["Survived"].mean().plot(kind="bar")
        plt.title(f"Survival Rate by {col}")
        plt.xlabel(col)
        plt.ylabel("Survival Rate")
        plt.xticks(rotation=0)

    plt.show()

from sklearn.model_selection import cross_val_score
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier

X = df.drop("Survived", axis=1)
y = df["Survived"]

models = {
    "Logistic Regression": LogisticRegression(max_iter=1000),
    "Decision Tree": DecisionTreeClassifier(),
    "Random Forest": RandomForestClassifier()
}

for name, model in models.items():
    scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")
    print(name, scores.mean())

from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [50, 100, 200],
    "max_depth": [3, 5, 10, None]
}

grid = GridSearchCV(
    RandomForestClassifier(),
    params,
    cv=5,
    scoring="accuracy"
)

grid.fit(X, y)

print(grid.best_params_)
print(grid.best_score_)

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import cross_val_score

gb = GradientBoostingClassifier(random_state=42)

scores = cross_val_score(gb, X, y, cv=5, scoring="accuracy")

print(scores.mean())

# 1. 特徴量追加
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

df["Male_Child"] = ((df["Sex_male"] == 1) & (df["Age"] < 16)).astype(int)
df["Male_HighFare"] = ((df["Sex_male"] == 1) & (df["Fare"] > df["Fare"].median())).astype(int)
df["Male_Family"] = ((df["Sex_male"] == 1) & (df["FamilySize"] > 1)).astype(int)

# 2. X, yを作り直す
X = df.drop("Survived", axis=1)
y = df["Survived"]

# 3. 学習・予測し直す
X_train, X_valid, y_train, y_valid = train_test_split(
    X, y, test_size=0.2, random_state=42
)

best_model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

best_model.fit(X_train, y_train)
pred = best_model.predict(X_valid)

# 4. 評価
print(accuracy_score(y_valid, pred))
print(confusion_matrix(y_valid, pred))
print(classification_report(y_valid, pred))

# 5. resultを作り直す
result = X_valid.copy()
result["actual"] = y_valid
result["pred"] = pred
result["is_miss"] = result["actual"] != result["pred"]

true_positive = result[(result["actual"] == 1) & (result["pred"] == 1)]
false_negative = result[(result["actual"] == 1) & (result["pred"] == 0)]

compare_fn = pd.DataFrame({
    "true_positive": true_positive.mean(numeric_only=True),
    "false_negative": false_negative.mean(numeric_only=True)
})

compare_fn["diff"] = compare_fn["false_negative"] - compare_fn["true_positive"]

compare_fn

# データを読み直す
df = pd.read_csv('/train.csv')

# 欠損値処理
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop("Cabin", axis=1)

# NameからTitleを抽出
df["Title"] = df["Name"].str.extract(" ([A-Za-z]+)\.", expand=False)

# 少数派のTitleをまとめる
df["Title"] = df["Title"].replace(
    ["Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
     "Rev", "Sir", "Jonkheer", "Dona"],
    "Rare"
)

df["Title"] = df["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})

# 家族系特徴量
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# 不要列を削除
df = df.drop(["PassengerId", "Name", "Ticket"], axis=1)

# カテゴリ変数をダミー化
df = pd.get_dummies(df, columns=["Sex", "Embarked", "Title"], drop_first=True)

# X, y
X = df.drop("Survived", axis=1)
y = df["Survived"]

df.head()

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")

print(scores)
print(scores.mean())

import pandas as pd

# データを読み直す
df = pd.read_csv('/train.csv')

# 欠損値処理
df["Age"] = df["Age"].fillna(df["Age"].median())
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df = df.drop("Cabin", axis=1)

# 家族系特徴量
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# Ageをビニング
df["Age_bin"] = pd.cut(
    df["Age"],
    bins=[0, 12, 18, 35, 60, 100],
    labels=["Child", "Teen", "YoungAdult", "Adult", "Senior"]
)

# Fareをビニング
df["Fare_bin"] = pd.qcut(
    df["Fare"],
    q=4,
    labels=["LowFare", "MidLowFare", "MidHighFare", "HighFare"]
)

# Pclass × Sex の交互作用特徴量
df["Pclass_Sex"] = df["Pclass"].astype(str) + "_" + df["Sex"]

# 不要列を削除
df = df.drop(["PassengerId", "Name", "Ticket"], axis=1)

# カテゴリ変数をダミー化
df = pd.get_dummies(
    df,
    columns=["Sex", "Embarked", "Age_bin", "Fare_bin", "Pclass_Sex"],
    drop_first=True
)

# X, y
X = df.drop("Survived", axis=1)
y = df["Survived"]

from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=10,
    random_state=42
)

scores = cross_val_score(model, X, y, cv=5, scoring="accuracy")

print(scores)
print(scores.mean())

params = {
    "n_estimators": [100, 200],
    "max_depth": [3, 5, 7],
    "min_samples_leaf": [2, 4],
    "max_features": ["sqrt"]
}

grid = GridSearchCV(
    RandomForestClassifier(random_state=42),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid.fit(X, y)

print(grid.best_params_)
print(grid.best_score_)

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [50, 100, 150],
    "learning_rate": [0.03, 0.05, 0.1],
    "max_depth": [2, 3, 4],
    "min_samples_leaf": [1, 2, 4]
}

grid_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_gb.fit(X, y)

print(grid_gb.best_params_)
print(grid_gb.best_score_)

from sklearn.model_selection import StratifiedKFold, cross_val_score

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

scores = cross_val_score(grid_gb.best_estimator_, X, y, cv=cv, scoring="accuracy")
print(scores)
print(scores.mean())

import pandas as pd

# データを読み直す
df = pd.read_csv('/train.csv')

# Embarked補完
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Ageを Sex × Pclass ごとの中央値で補完
df["Age"] = df.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabin欠損フラグ
df["HasCabin"] = df["Cabin"].notnull().astype(int)

# Ticketグループ人数
df["TicketGroupSize"] = df.groupby("Ticket")["Ticket"].transform("count")

# Cabinは削除
df = df.drop("Cabin", axis=1)

# 家族系特徴量
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# 不要列削除
df = df.drop(["PassengerId", "Name", "Ticket"], axis=1)

# 最後にダミー化
df = pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True)

# X, y
X = df.drop("Survived", axis=1)
y = df["Survived"]

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [100, 150, 200],
    "learning_rate": [0.05, 0.1],
    "max_depth": [3, 4],
    "min_samples_leaf": [1, 2]
}

grid_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_gb.fit(X, y)

print(grid_gb.best_params_)
print(grid_gb.best_score_)

import pandas as pd

# データを読み直す
df = pd.read_csv('/train.csv')

# Embarked補完
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Ageを Sex × Pclass ごとの中央値で補完
df["Age"] = df.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabinを消す前に、Cabinの有無を特徴量化
df["HasCabin"] = df["Cabin"].notnull().astype(int)

# Ticketを消す前に、同じTicketの人数を特徴量化
df["TicketGroupSize"] = df.groupby("Ticket")["Ticket"].transform("count")

# 家族系特徴量
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# 不要列を最後に削除
df = df.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

# カテゴリ変数をダミー化
df = pd.get_dummies(df, columns=["Sex", "Embarked"], drop_first=True)

# X, y
X = df.drop("Survived", axis=1)
y = df["Survived"]

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [100, 150, 200],
    "learning_rate": [0.05, 0.1],
    "max_depth": [3, 4],
    "min_samples_leaf": [1, 2]
}

grid_gb = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_gb.fit(X, y)

print(grid_gb.best_params_)
print(grid_gb.best_score_)

from sklearn.ensemble import HistGradientBoostingClassifier
from sklearn.model_selection import cross_val_score, StratifiedKFold

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

hgb = HistGradientBoostingClassifier(
    max_iter=200,
    learning_rate=0.05,
    max_leaf_nodes=15,
    random_state=42
)

scores = cross_val_score(hgb, X, y, cv=cv, scoring="accuracy")
print(scores)
print(scores.mean())

df.head()

import pandas as pd

# データを読み直す
df = pd.read_csv('/train.csv')

# Embarked補完
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])

# Ageを Sex × Pclass ごとの中央値で補完
df["Age"] = df.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabin関連特徴量
df["HasCabin"] = df["Cabin"].notnull().astype(int)

# Deck抽出：Cabinの先頭文字を使う。欠損はUnknown
df["Deck"] = df["Cabin"].str[0]
df["Deck"] = df["Deck"].fillna("Unknown")

# TicketGroupSize
df["TicketGroupSize"] = df.groupby("Ticket")["Ticket"].transform("count")

# 家族系特徴量
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# 不要列削除
df = df.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

# カテゴリ変数をダミー化
df = pd.get_dummies(
    df,
    columns=["Sex", "Embarked", "Deck"],
    drop_first=True
)

# X, y
X = df.drop("Survived", axis=1)
y = df["Survived"]

from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [150, 200, 250],
    "learning_rate": [0.05, 0.1],
    "max_depth": [2, 3, 4],
    "min_samples_leaf": [1, 2, 4]
}

grid_gb_deck = GridSearchCV(
    GradientBoostingClassifier(random_state=42),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_gb_deck.fit(X, y)

print(grid_gb_deck.best_params_)
print(grid_gb_deck.best_score_)

!pip install xgboost

from xgboost import XGBClassifier
from sklearn.model_selection import GridSearchCV

params = {
    "n_estimators": [100, 200, 300],
    "learning_rate": [0.03, 0.05, 0.1],
    "max_depth": [2, 3, 4],
    "subsample": [0.8, 1.0],
    "colsample_bytree": [0.8, 1.0]
}

grid_xgb = GridSearchCV(
    XGBClassifier(
        random_state=42,
        eval_metric="logloss"
    ),
    params,
    cv=5,
    scoring="accuracy",
    n_jobs=-1
)

grid_xgb.fit(X, y)

print(grid_xgb.best_params_)
print(grid_xgb.best_score_)

import pandas as pd
from xgboost import XGBClassifier

# train / test 読み込み
train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

# trainとtestを結合して、同じ前処理をかける
train["is_train"] = 1
test["is_train"] = 0
test["Survived"] = None

df_all = pd.concat([train, test], axis=0)

# Embarked補完
df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])

# Fare補完
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# Ageを Sex × Pclass ごとの中央値で補完
df_all["Age"] = df_all.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabin関連
df_all["HasCabin"] = df_all["Cabin"].notnull().astype(int)
df_all["Deck"] = df_all["Cabin"].str[0].fillna("Unknown")

# TicketGroupSize
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

# 家族系特徴量
df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)

# 不要列削除
df_all = df_all.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

# ダミー化
df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Deck"],
    drop_first=True
)

# train / test に戻す
train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)

# XGBoost 最良パラメータ
model = XGBClassifier(
    n_estimators=300,
    learning_rate=0.05,
    max_depth=4,
    subsample=1.0,
    colsample_bytree=1.0,
    random_state=42,
    eval_metric="logloss"
)

# train全体で学習
model.fit(X, y)

# test予測
pred = model.predict(test_processed)

# 提出ファイル作成
submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission.csv", index=False)

submission.head()

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=200,
    max_depth=5,
    min_samples_leaf=3,
    random_state=42
)

model.fit(X, y)
pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_rf_simple.csv", index=False)
submission.head()

from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X, y)
pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_xgb_simple.csv", index=False)
submission.head()

from xgboost import XGBClassifier

model = XGBClassifier(
    n_estimators=150,
    learning_rate=0.03,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    reg_lambda=2,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X, y)
pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_xgb_regularized.csv", index=False)
submission.head()

import pandas as pd
from xgboost import XGBClassifier

# train / test 読み込み
train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

# trainとtestを結合
train["is_train"] = 1
test["is_train"] = 0
test["Survived"] = None

df_all = pd.concat([train, test], axis=0)

# Embarked補完
df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])

# Fare補完
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# Ageを Sex × Pclass ごとの中央値で補完
df_all["Age"] = df_all.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabin関連特徴量
df_all["HasCabin"] = df_all["Cabin"].notnull().astype(int)
df_all["Deck"] = df_all["Cabin"].str[0].fillna("Unknown")

# Ticketを消す前にTicketGroupSizeを作る
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

# TicketGroupSizeを作った後にFarePerPersonを作る
df_all["FarePerPerson"] = df_all["Fare"] / df_all["TicketGroupSize"]
df_all["FarePerPerson"] = df_all["FarePerPerson"].fillna(df_all["FarePerPerson"].median())

# 家族系特徴量
df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)

# ここで初めて不要列を削除
df_all = df_all.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

# ダミー化
df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Deck"],
    drop_first=True
)

# train / test に戻す
train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)

# 現状最高だった弱めXGBoost
model = XGBClassifier(
    n_estimators=100,
    learning_rate=0.05,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X, y)

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_xgb_fare_per_person.csv", index=False)
submission.head()

import pandas as pd
from xgboost import XGBClassifier

# =========================
# 1. train / test 読み込み
# =========================

train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

# train / test を区別する列を追加
train["is_train"] = 1
test["is_train"] = 0

# testにはSurvivedがないので仮で追加
test["Survived"] = None

# trainとtestを結合
df_all = pd.concat([train, test], axis=0)


# =========================
# 2. 欠損値処理
# =========================

# Embarkedは最頻値で補完
df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])

# Fareは中央値で補完
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# Ageは Sex × Pclass ごとの中央値で補完
df_all["Age"] = df_all.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)


# =========================
# 3. Nameから敬称Titleを抽出
# =========================

df_all["Title"] = df_all["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

# 少数派の敬称をRareにまとめる
df_all["Title"] = df_all["Title"].replace(
    [
        "Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
        "Rev", "Sir", "Jonkheer", "Dona"
    ],
    "Rare"
)

# 表記ゆれを統一
df_all["Title"] = df_all["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})


# =========================
# 4. 家族人数などの特徴量追加
# =========================

# 家族人数
df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1

# 1人で乗船しているか
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)

# 子供かどうか
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)


# =========================
# 5. Cabin / Ticket由来の特徴量追加
# =========================

# Cabinがあるかどうか
df_all["HasCabin"] = df_all["Cabin"].notnull().astype(int)

# Cabinの先頭文字をDeckとして抽出
df_all["Deck"] = df_all["Cabin"].str[0].fillna("Unknown")

# 同じTicketを持つ人数
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

# 1人あたり運賃
df_all["FarePerPerson"] = df_all["Fare"] / df_all["TicketGroupSize"]
df_all["FarePerPerson"] = df_all["FarePerPerson"].fillna(df_all["FarePerPerson"].median())


# =========================
# 6. 不要列を削除
# =========================

df_all = df_all.drop(
    ["PassengerId", "Name", "Cabin", "Ticket"],
    axis=1
)


# =========================
# 7. カテゴリ変数をダミー化
# =========================

df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Title", "Deck"],
    drop_first=True
)


# =========================
# 8. train / test に戻す
# =========================

train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)


# =========================
# 9. モデル学習
# =========================

model = XGBClassifier(
    n_estimators=150,
    learning_rate=0.03,
    max_depth=2,
    subsample=0.8,
    colsample_bytree=0.8,
    min_child_weight=3,
    reg_lambda=2,
    random_state=42,
    eval_metric="logloss"
)

model.fit(X, y)


# =========================
# 10. test予測・提出ファイル作成
# =========================

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_title_family.csv", index=False)

submission.head()

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=4,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model.fit(X, y)

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_rf_conservative.csv", index=False)

submission.head()

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# =========================
# 1. train / test 読み込み
# =========================

train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

train["is_train"] = 1
test["is_train"] = 0
test["Survived"] = None

df_all = pd.concat([train, test], axis=0)


# =========================
# 2. NameからTitleを先に抽出
# =========================

df_all["Title"] = df_all["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

# 少数派TitleをRareにまとめる
df_all["Title"] = df_all["Title"].replace(
    [
        "Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
        "Rev", "Sir", "Jonkheer", "Dona"
    ],
    "Rare"
)

# 表記ゆれを統一
df_all["Title"] = df_all["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})


# =========================
# 3. 欠損値処理
# =========================

# Embarkedは最頻値で補完
df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])

# Fareは中央値で補完
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# AgeはTitleごとの中央値で補完
df_all["Age"] = df_all.groupby("Title")["Age"].transform(
    lambda x: x.fillna(x.median())
)

# それでも埋まらない場合は全体中央値で補完
df_all["Age"] = df_all["Age"].fillna(df_all["Age"].median())


# =========================
# 4. 特徴量追加
# =========================

# 家族人数
df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1

# 一人乗船
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)

# 子供
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)

# TicketGroupSize
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

# 1人あたり運賃
df_all["FarePerPerson"] = df_all["Fare"] / df_all["TicketGroupSize"]
df_all["FarePerPerson"] = df_all["FarePerPerson"].fillna(df_all["FarePerPerson"].median())


# =========================
# 5. 寄与が低そうな特徴量を削る
# =========================
# Deck / HasCabin は今回は作らない
# Cabinは欠損が多く、Public Scoreではノイズになりやすいため削除

df_all = df_all.drop(
    ["PassengerId", "Name", "Cabin", "Ticket"],
    axis=1
)


# =========================
# 6. カテゴリ変数をダミー化
# =========================

df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Title"],
    drop_first=True
)


# =========================
# 7. train / test に戻す
# =========================

train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)


# =========================
# 8. RandomForestで学習
# =========================

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=4,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model.fit(X, y)


# =========================
# 9. test予測・提出ファイル作成
# =========================

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_rf_title_age_no_deck.csv", index=False)

submission.head()

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# =========================
# 1. train / test 読み込み
# =========================

train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

train["is_train"] = 1
test["is_train"] = 0
test["Survived"] = None

df_all = pd.concat([train, test], axis=0)


# =========================
# 2. NameからTitleを先に抽出
# =========================

df_all["Title"] = df_all["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

df_all["Title"] = df_all["Title"].replace(
    [
        "Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
        "Rev", "Sir", "Jonkheer", "Dona"
    ],
    "Rare"
)

df_all["Title"] = df_all["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})


# =========================
# 3. 欠損値処理
# =========================

df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# AgeをTitleごとの中央値で補完
df_all["Age"] = df_all.groupby("Title")["Age"].transform(
    lambda x: x.fillna(x.median())
)

# 念のため全体中央値で補完
df_all["Age"] = df_all["Age"].fillna(df_all["Age"].median())


# =========================
# 4. 特徴量追加
# =========================

df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)

# Cabin関連は戻す
df_all["HasCabin"] = df_all["Cabin"].notnull().astype(int)
df_all["Deck"] = df_all["Cabin"].str[0].fillna("Unknown")

# Ticket関連
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

df_all["FarePerPerson"] = df_all["Fare"] / df_all["TicketGroupSize"]
df_all["FarePerPerson"] = df_all["FarePerPerson"].fillna(df_all["FarePerPerson"].median())


# =========================
# 5. 不要列削除
# =========================

df_all = df_all.drop(
    ["PassengerId", "Name", "Cabin", "Ticket"],
    axis=1
)


# =========================
# 6. ダミー化
# =========================

df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Title", "Deck"],
    drop_first=True
)


# =========================
# 7. train / test に戻す
# =========================

train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)


# =========================
# 8. RandomForest
# =========================

model = RandomForestClassifier(
    n_estimators=300,
    max_depth=4,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model.fit(X, y)

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_rf_title_age_with_deck.csv", index=False)

submission.head()

best = pd.read_csv("submission_rf_conservative.csv")
new = pd.read_csv("submission_rf_title_age_with_deck.csv")

diff = best["Survived"] != new["Survived"]

print("予測が変わった人数:", diff.sum())
print("全体に占める割合:", diff.mean())

pd.DataFrame({
    "PassengerId": best.loc[diff, "PassengerId"],
    "best_pred": best.loc[diff, "Survived"],
    "new_pred": new.loc[diff, "Survived"]
}).head(20)

from sklearn.ensemble import RandomForestClassifier

model = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model.fit(X, y)

pred = model.predict(test_processed)

submission = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred.astype(int)
})

submission.to_csv("submission_rf_kakuchou.csv", index=False)

submission.head()

best = pd.read_csv("submission_rf_conservative.csv")
new = pd.read_csv("submission_rf_kakuchou.csv")

diff = best["Survived"] != new["Survived"]

print("予測が変わった人数:", diff.sum())
print("全体に占める割合:", diff.mean())

pd.DataFrame({
    "PassengerId": best.loc[diff, "PassengerId"],
    "best_pred": best.loc[diff, "Survived"],
    "new_pred": new.loc[diff, "Survived"]
}).head(20)

import pandas as pd
import numpy as np

from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import StratifiedKFold, cross_val_score

# =========================
# 1. train読み込み
# =========================

train = pd.read_csv('/train.csv')

# =========================
# 2. 最高スコア構成の前処理を再現
# =========================

df = train.copy()

# Title抽出
df["Title"] = df["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

df["Title"] = df["Title"].replace(
    [
        "Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
        "Rev", "Sir", "Jonkheer", "Dona"
    ],
    "Rare"
)

df["Title"] = df["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})

# 欠損値補完
df["Embarked"] = df["Embarked"].fillna(df["Embarked"].mode()[0])
df["Fare"] = df["Fare"].fillna(df["Fare"].median())

# Ageは Sex × Pclass ごとの中央値で補完
df["Age"] = df.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)

# Cabin / Deck
df["HasCabin"] = df["Cabin"].notnull().astype(int)
df["Deck"] = df["Cabin"].str[0].fillna("Unknown")

# Ticket
df["TicketGroupSize"] = df.groupby("Ticket")["Ticket"].transform("count")

# FarePerPerson
df["FarePerPerson"] = df["Fare"] / df["TicketGroupSize"]
df["FarePerPerson"] = df["FarePerPerson"].fillna(df["FarePerPerson"].median())

# 家族系
df["FamilySize"] = df["SibSp"] + df["Parch"] + 1
df["IsAlone"] = (df["FamilySize"] == 1).astype(int)
df["IsChild"] = (df["Age"] < 16).astype(int)

# 不要列削除
df = df.drop(["PassengerId", "Name", "Cabin", "Ticket"], axis=1)

# ダミー化
df = pd.get_dummies(
    df,
    columns=["Sex", "Embarked", "Title", "Deck"],
    drop_first=True
)

X = df.drop("Survived", axis=1)
y = df["Survived"].astype(int)

# =========================
# 3. 比較する2モデル
# =========================

model_conservative = RandomForestClassifier(
    n_estimators=300,
    max_depth=4,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model_kakuchou = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

# =========================
# 4. 同じCV分割で比較
# =========================

cv = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)

score_conservative = cross_val_score(
    model_conservative, X, y, cv=cv, scoring="accuracy"
)

score_kakuchou = cross_val_score(
    model_kakuchou, X, y, cv=cv, scoring="accuracy"
)

print("conservative scores:", score_conservative)
print("conservative mean:", score_conservative.mean())

print("kakuchou scores:", score_kakuchou)
print("kakuchou mean:", score_kakuchou.mean())

print("差分:", score_kakuchou.mean() - score_conservative.mean())

from sklearn.model_selection import cross_val_predict
from sklearn.metrics import accuracy_score

pred_conservative_oof = cross_val_predict(
    model_conservative, X, y, cv=cv
)

pred_kakuchou_oof = cross_val_predict(
    model_kakuchou, X, y, cv=cv
)

diff = pred_conservative_oof != pred_kakuchou_oof

print("CV上で予測が変わった人数:", diff.sum())
print("全体に占める割合:", diff.mean())

print("conservative 全体精度:", accuracy_score(y, pred_conservative_oof))
print("kakuchou 全体精度:", accuracy_score(y, pred_kakuchou_oof))

print("予測が変わった人だけの conservative 精度:")
print(accuracy_score(y[diff], pred_conservative_oof[diff]))

print("予測が変わった人だけの kakuchou 精度:")
print(accuracy_score(y[diff], pred_kakuchou_oof[diff]))

import pandas as pd
from sklearn.ensemble import RandomForestClassifier

# =========================
# 1. train / test 読み込み
# =========================

train = pd.read_csv('/train.csv')
test = pd.read_csv('/test.csv')

test_passenger_id = test["PassengerId"]

train["is_train"] = 1
test["is_train"] = 0
test["Survived"] = None

df_all = pd.concat([train, test], axis=0)


# =========================
# 2. Title抽出
# =========================

df_all["Title"] = df_all["Name"].str.extract(r" ([A-Za-z]+)\.", expand=False)

df_all["Title"] = df_all["Title"].replace(
    [
        "Lady", "Countess", "Capt", "Col", "Don", "Dr", "Major",
        "Rev", "Sir", "Jonkheer", "Dona"
    ],
    "Rare"
)

df_all["Title"] = df_all["Title"].replace({
    "Mlle": "Miss",
    "Ms": "Miss",
    "Mme": "Mrs"
})


# =========================
# 3. 欠損値処理
# =========================

df_all["Embarked"] = df_all["Embarked"].fillna(df_all["Embarked"].mode()[0])
df_all["Fare"] = df_all["Fare"].fillna(df_all["Fare"].median())

# 最高スコア構成に合わせて、Ageは Sex × Pclass ごとの中央値で補完
df_all["Age"] = df_all.groupby(["Sex", "Pclass"])["Age"].transform(
    lambda x: x.fillna(x.median())
)


# =========================
# 4. 特徴量作成
# =========================

# 家族系
df_all["FamilySize"] = df_all["SibSp"] + df_all["Parch"] + 1
df_all["IsAlone"] = (df_all["FamilySize"] == 1).astype(int)
df_all["IsChild"] = (df_all["Age"] < 16).astype(int)

# Cabin系
df_all["HasCabin"] = df_all["Cabin"].notnull().astype(int)
df_all["Deck"] = df_all["Cabin"].str[0].fillna("Unknown")

# Ticket系
df_all["TicketGroupSize"] = df_all.groupby("Ticket")["Ticket"].transform("count")

# FarePerPerson
df_all["FarePerPerson"] = df_all["Fare"] / df_all["TicketGroupSize"]
df_all["FarePerPerson"] = df_all["FarePerPerson"].fillna(
    df_all["FarePerPerson"].median()
)


# =========================
# 5. 不要列削除
# =========================

df_all = df_all.drop(
    ["PassengerId", "Name", "Cabin", "Ticket"],
    axis=1
)


# =========================
# 6. ダミー化
# =========================

df_all = pd.get_dummies(
    df_all,
    columns=["Sex", "Embarked", "Title", "Deck"],
    drop_first=True
)


# =========================
# 7. train / test に戻す
# =========================

train_processed = df_all[df_all["is_train"] == 1].drop("is_train", axis=1)
test_processed = df_all[df_all["is_train"] == 0].drop(["is_train", "Survived"], axis=1)

X = train_processed.drop("Survived", axis=1)
y = train_processed["Survived"].astype(int)


# =========================
# 8. conservativeモデル
# =========================

model_conservative = RandomForestClassifier(
    n_estimators=300,
    max_depth=4,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model_conservative.fit(X, y)

pred_conservative = model_conservative.predict(test_processed)

submission_conservative = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred_conservative.astype(int)
})

submission_conservative.to_csv("submission_rf_conservative_remake.csv", index=False)


# =========================
# 9. kakuchouモデル
# =========================

model_kakuchou = RandomForestClassifier(
    n_estimators=500,
    max_depth=5,
    min_samples_leaf=4,
    max_features="sqrt",
    random_state=42
)

model_kakuchou.fit(X, y)

pred_kakuchou = model_kakuchou.predict(test_processed)

submission_kakuchou = pd.DataFrame({
    "PassengerId": test_passenger_id,
    "Survived": pred_kakuchou.astype(int)
})

submission_kakuchou.to_csv("submission_rf_kakuchou_remake.csv", index=False)


# =========================
# 10. 差分比較
# =========================

diff = submission_conservative["Survived"] != submission_kakuchou["Survived"]

print("予測が変わった人数:", diff.sum())
print("全体に占める割合:", diff.mean())

diff_df = pd.DataFrame({
    "PassengerId": submission_conservative.loc[diff, "PassengerId"],
    "conservative_pred": submission_conservative.loc[diff, "Survived"],
    "kakuchou_pred": submission_kakuchou.loc[diff, "Survived"]
})

diff_df